In [1]:
import numpy
n = numpy.arange(27)

In [2]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [4]:
a = numpy.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a = numpy.array([(0,1,2,3,4,5),(6,7,8,9,10,11)])
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [6]:
a = numpy.array([(0,1,2,3,4,5),(6,7,8,9,10,11)])

In [7]:
print(a.ndim)


2


In [9]:
import cv2 


In [10]:
cv2

<module 'cv2' from '/home/uday/anaconda3/lib/python3.7/site-packages/cv2.cpython-37m-x86_64-linux-gnu.so'>

In [11]:
im_g = cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
cv2.imwrite("newsmallgrey.png",im_g)

True