In [1]:
import numpy
n = numpy.arange(27)

In [2]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [4]:
a = numpy.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a = numpy.array([(0,1,2,3,4,5),(6,7,8,9,10,11)])
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [6]:
a = numpy.array([(0,1,2,3,4,5),(6,7,8,9,10,11)])

In [7]:
print(a.ndim)


2


In [8]:
import cv2 


In [9]:
cv2

<module 'cv2' from '/home/uday/anaconda3/lib/python3.7/site-packages/cv2.cpython-37m-x86_64-linux-gnu.so'>

In [10]:
im_g = cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
cv2.imwrite("newsmallgrey.png",im_g)

True

In [14]:
import folium

In [15]:
dir(folium)

['Choropleth',
 'Circle',
 'CircleMarker',
 'ClickForMarker',
 'ColorLine',
 'ColorMap',
 'CssLink',
 'CustomIcon',
 'Div',
 'DivIcon',
 'Element',
 'FeatureGroup',
 'Figure',
 'FitBounds',
 'GeoJson',
 'GeoJsonTooltip',
 'Html',
 'IFrame',
 'Icon',
 'JavascriptLink',
 'LatLngPopup',
 'LayerControl',
 'LinearColormap',
 'Link',
 'MacroElement',
 'Map',
 'Marker',
 'PolyLine',
 'Polygon',
 'Popup',
 'Rectangle',
 'RegularPolygonMarker',
 'StepColormap',
 'TileLayer',
 'Tooltip',
 'TopoJson',
 'Vega',
 'VegaLite',
 'WmsTileLayer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_version',
 'branca',
 'features',
 'folium',
 'map',
 'raster_layers',
 'sys',
 'utilities',
 'vector_layers']

In [16]:
help(folium.Map)

Help on class Map in module folium.folium:

class Map(branca.element.MacroElement)
 |  Map(location=None, width='100%', height='100%', left='0%', top='0%', position='relative', tiles='OpenStreetMap', attr=None, min_zoom=0, max_zoom=18, zoom_start=10, min_lat=-90, max_lat=90, min_lon=-180, max_lon=180, max_bounds=False, crs='EPSG3857', control_scale=False, prefer_canvas=False, no_touch=False, disable_3d=False, png_enabled=False, zoom_control=True, **kwargs)
 |  
 |  Create a Map with Folium and Leaflet.js
 |  
 |  Generate a base map of given width and height with either default
 |  tilesets or a custom tileset URL. The following tilesets are built-in
 |  to Folium. Pass any of the following to the "tiles" keyword:
 |  
 |      - "OpenStreetMap"
 |      - "Mapbox Bright" (Limited levels of zoom for free tiles)
 |      - "Mapbox Control Room" (Limited levels of zoom for free tiles)
 |      - "Stamen" (Terrain, Toner, and Watercolor)
 |      - "Cloudmade" (Must pass API key)
 |      - "Ma

In [36]:
map = folium.Map(location=[38.58, -99.09], zoom_start=6)

In [38]:
fg = folium.FeatureGroup(name="My Map")

In [39]:
for coordinates in [[38.2, -99.1], [25.2, -90.1]]:
    fg.add_child(folium.Marker(location=coordinates,
                               popup="Hi I'm a marker", icon=folium.Icon(color='green')))


In [40]:
map.save("Map1.html")

In [41]:
map

In [42]:
pandas

NameError: name 'pandas' is not defined

In [43]:
import pandas

In [44]:
pandas

<module 'pandas' from '/home/uday/anaconda3/lib/python3.7/site-packages/pandas/__init__.py'>